plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.10-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.107' apply false
    id 'org.jetbrains.kotlin.jvm' version '2.2.0' apply false
}

tasks.register("publish-local") {
    group("build")
    description = "将 Fabric 和 NeoForge 的内容发布到本地 Maven 仓库"
    dependsOn(
            ":neoforge:publishMavenJavaPublicationToMavenLocal",
            ":fabric:publishMavenJavaPublicationToMavenLocal"
    )
}

tasks.register("publish-all") {
    group("build")
    description = "将 Fabric 和 NeoForge 的内容发布到本地 Maven 和远程仓库"
    dependsOn(
            "publish-local",
            ":neoforge:publishMavenJavaPublicationToRepoRepository",
            ":fabric:publishMavenJavaPublicationToRepoRepository"
    )
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'kotlin'
    apply plugin: 'maven-publish'

    repositories {
        mavenCentral()
        maven {
            name = 'NeoForge'
            url = uri('https://maven.neoforged.net/releases')
            content {
                includeGroupAndSubgroups('net.neoforged')
            }
        }
    }

    sourceSets {
        main {
            kotlin {
                srcDir("${project(":common").buildDir}/generated/source/kapt/main")
            }
            java {
                srcDir("${project(":common").buildDir}/generated/source/kapt/main")
            }
        }
        main.kotlin.srcDirs = ['src/main/java',
                               'src/main/kotlin'
        ]
    }
    compileKotlin {
            source(project(":common").sourceSets.main.allSource)
            inputs.file "../gradle.properties"
    }
    afterEvaluate {
        def sourcesJar = tasks.findByName("sourcesJar")
        if (sourcesJar != null) {
            sourcesJar.duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }
        def jarTask = tasks.findByName("jar")
        if (jarTask != null) {
            jarTask.duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }
    }
}
